---
# Source: ghost/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: ghost
  namespace: "default"
  labels:
    app.kubernetes.io/name: ghost
    helm.sh/chart: ghost-15.1.0
    app.kubernetes.io/instance: ghost
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  ghost-password: "Mm5zRXE2cmY3Wg=="
