---
# Source: ghost/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-ghost
  namespace: "default"
  labels:
    app.kubernetes.io/name: ghost
    helm.sh/chart: ghost-19.0.8
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: ghost
  annotations:
automountServiceAccountToken: true
