---
# Source: ghost/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-ghost
  namespace: "default"
  labels:
    app.kubernetes.io/name: ghost
    helm.sh/chart: ghost-19.0.8
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: ghost
spec:
  type: LoadBalancer
  externalTrafficPolicy: "Cluster"
  sessionAffinity: None
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/name: ghost
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/component: ghost
