apiVersion: cloudDeploy/beta1
kind: delivery-pipeline
name: web-app
description: web-app delivery pipeline
serialPipeline:
 stages:
 - targetId: default
---
apiVersion: cloudDeploy/beta1
kind: target
name: default
delivery-pipeline: web-app
description: default
gkeCluster:
  project: vic-e2e-cicd
  cluster: default
  location: us-west2