apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../bases/mysql
patches:
- path: pass-patch.yaml
  target:
    kind: Deployment
commonLabels:
    environ: prod-db
namePrefix: prod-
namespace: db
