apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
spec:
  selector:
    matchLabels:
      app: ghost
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - name: ghost
        image: ghost:3-alpine
        ports:
        - containerPort: 2368
        env:
          # see https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables
          - name: database__client
            value: mysql
          - name: database__connection__host
            value: db
          - name: database__connection__user
            value: root
          - name: database__connection__password
            value: changeme! # {"$kpt-set":"mysqlpw"}
          - name: database__connection__database
            value: ghost
          # this url value is just an example, and is likely wrong for your environment!
          - name: url
            value: http://localhost:8080