apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
spec:
  selector:
    matchLabels:
      app: ghost
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - name: ghost
        image: ghost:3-alpine
        ports:
        - containerPort: 2368
        env:
        - name: url # this url value is just an example, and is likely wrong for your environment!
          value: http://localhost:8080
