apiVersion: v1
kind: ConfigMap
metadata:
  name: local-cm-demo

annotations:
  config.kubernetes.io/local-config: "true" # tools should ignore this
  
data:
  character: "orc"
  mood: "angry"
  strength: "+3"
